version: '3.8'

services:
  wedding-guest-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: wedding-guest-portal-fe
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Development service (optional)
  wedding-guest-portal-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    container_name: wedding-guest-portal-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
